orgs:
  stephengrier-org:
    admins:
    - stephengrier
    - stephengrier-org-bot
    billing_email: stephen@stephengrier.com
    company: ""
    default_repository_permission: read
    description: "Org for testing various IaC tools for managing GitHub orgs"
    email: ""
    has_organization_projects: true
    has_repository_projects: true
    location: ""
    members_can_create_repositories: false
    name: ""
